#!/bin/sh

certbot=/certbot
letsencrypt=/etc/letsencrypt
certs=$letsencrypt/certs
config=~/.config/letsencrypt/domains

mkdir -p $certs

code=1

certonly() {
	certbot certonly -d "$1" --agree-tos -n || exit 2
	domain=${1/\*./}
	[ 1 ] && \
		[ -f $certs/$domain.crt ] && \
		[ -f $certs/$domain.key ] && \
		cmp -s $certs/$domain.crt $letsencrypt/live/$domain/fullchain.pem && \
		cmp -s $certs/$domain.key $letsencrypt/live/$domain/privkey.pem && \
		return
	cp $letsencrypt/live/$domain/fullchain.pem $certs/$domain.crt
	cp $letsencrypt/live/$domain/privkey.pem $certs/$domain.key
	code=0
}

if [ $# != 0 ]; then
	for domain in $*; do
		certonly $domain
	done
elif [ -f $config ]; then
	while read domain; do
		certonly $domain
	done < $config
fi

exit $code
