#!/bin/sh

. dns-dnspod

DOMAIN=`echo $CERTBOT_DOMAIN | grep -oP '[^.]+\.[^.]+$'`
SUB_DOMAIN=`echo $CERTBOT_DOMAIN | sed -r 's/\.?[^.]+\.[^.]+$//'`
LOG_DIR=/tmp/CERTBOT_$CERTBOT_DOMAIN

if [ $SUB_DOMAIN ]; then
	SUB_DOMAIN=_acme-challenge.$SUB_DOMAIN
else
	SUB_DOMAIN=_acme-challenge
fi

[ -d $LOG_DIR ] || mkdir -m 700 $LOG_DIR

echo add domain ${SUB_DOMAIN}.${DOMAIN}: $CERTBOT_VALIDATION
curl -sS -X POST -d "$LOGIN_TOKEN&format=json&domain=$DOMAIN&sub_domain=$SUB_DOMAIN&record_type=TXT&record_line_id=0&value=$CERTBOT_VALIDATION" https://dnsapi.cn/Record.Create > $LOG_DIR/dns.log || exit 1
RECORD_ID=`cat $LOG_DIR/dns.log | jq -r .record.id | tee $LOG_DIR/RECORD_ID`

if [ $RECORD_ID = null ]; then
	cat $LOG_DIR/dns.log | jq -r .status.message
	exit 2
fi

echo record id: $RECORD_ID
sleep 1m
