#!/bin/bash

prefix=/git

filename()
{
	filename=`basename $1`
	echo ${filename%.*}
}

sync-repo()
{
	repo=$1
	[ "$dir" ] || dir=$(filename $repo)
	dir=$prefix/$2
	[ -d $dir ] || git clone --mirror $repo $dir
	echo -n "$2: "
	cd $dir
	git remote update
}

[ ~/.git-sync ] && . ~/.git-sync